### ISSUE TITLE
Resolve values when exporting data

### ISSUE THREAD

**Issue by rolandschaub** [luyadev/luya-module-contactform#13]
When exporting the submission data of a form, key values from checkboxes, radio buttons and selects should be resolved to their "definite" values, e.g. "Mr" and "Mrs" instead of "1" and "2", as otherwise the values have to be resolved manually after the export, which is a pain and error prone.

This is how it looks currently:

<img width="229" alt="export" src="https://user-images.githubusercontent.com/3786245/33900109-ba7d8c82-df6d-11e7-8695-1e5d3814ce20.png">

**Comment by nadar** [comment]
@rolandschaub the luya contactform module does not have any admin interface. So this is should be either a part of the admin module or must be solved in your application.
