### ISSUE TITLE
Preview form inputs before submit

### ISSUE THREAD

**Issue by dev7ch** [luyadev/luya-module-contactform#8]
The option to review the form inputs before submitting the form would be very helpful.

**Comment by rolandschaub** [comment]
This is an important feature for some situations, e.g. with registration or order forms (especially if costs are involved), or with other complex forms where it's easy for the user to make a mistake.

**Comment by martinpetrasch** [comment]
Thanks for the input! To avoid duplicates, I'll close this issue and will continue solving this issue in #9
