### ISSUE TITLE
Enable confirmation page with access to form model data

### ISSUE THREAD

**Issue by rolandschaub** [luyadev/luya-module-contactform#9]
After a form is successfully submitted, it should be possible to use the submitted form data in the confirmation page that is displayed. As it is now the form model is empty after submission. That is okay as long as there is another way to retrieve the data.

**Comment by martinpetrasch** [comment]
This should be done by saving the dynamic model into a configurable session var. In the confirmation step you initialize the model again for view output and following callbacks. The original form step should check for this session var to preinitializing the model. Finishing the confirmation step should also clear the session var.

**Comment by nadar** [comment]
@martinpetrasch aren't you talk about this => https://github.com/luyadev/luya-module-contactform/issues/8 or its almost the same? so we could close #8

**Comment by nadar** [comment]
use https://github.com/luyadev/luya-module-forms instead
